-- Baseline seed data snapshot
-- Generated by dump_migrations.py on 2026-07-06T22:41:19Z
-- Apply AFTER 0001_baseline_schema.sql
-- To re-apply: psql $BIZZAL_DB_URL < db/migrations/0002_baseline_seed_data.sql

-- rpg_systems
DELETE FROM rpg_systems;
INSERT INTO rpg_systems (id,display_name,chain_tag,path_suffix,is_active,ruleset,target_seconds,reading_level,no_homebrew_mechanics,default_length,spice_rate,persona_default,voiceover_default_voice_pack_id,voiceover_default_tts_voice_id,active_srd_path,srd_pdf_path,reference_sources,bg_image_prompt_prefix,bg_image_prompt_suffix,music_prompt_prefix,music_prompt_suffix,enable_ai,enable_ai_script,enable_tts,enable_bg_image,enable_bg_music,enable_pdf_flavor,tts_voice_variety_lookback_days) VALUES ('dnd5e','D&D 5e','D&D','',true,'wotc_srd_2024',55,'general',true,'shorts',0.6,'wry_vet','voice-friendly-vet','alloy','reference/systems/dnd5e/active','reference/systems/dnd5e/source_pdfs/SRD_CC_v5.2.1.pdf','{"items": {"also": {"armor": "Armor.json", "weapons": "Weapon.json", "weapon_properties": "WeaponProperty.json", "weapon_property_assignments": "WeaponPropertyAssignment.json"}, "file": "Item.json", "joins": {"item_category": "ItemCategory.json"}}, "rules": {"file": "Rule.json", "joins": {"rulesets": "RuleSet.json"}}, "flavor": {"ability": "AbilityDescription.json", "alignment": "AlignmentDescription.json", "condition": "ConditionDescription.json", "damage_type": "DamageTypeDescription.json", "environment": null, "creature_type": "CreatureTypeDescription.json"}, "spells": {"file": "Spell.json", "joins": {"casting_options": "SpellCastingOption.json"}}, "classes": {"file": "CharacterClass.json", "joins": {"features": "ClassFeature.json", "feature_items": "ClassFeatureItem.json"}}, "species": {"file": "Species.json", "joins": {"traits": "SpeciesTrait.json"}}, "creatures": {"file": "Creature.json", "joins": {"traits": "CreatureTrait.json", "actions": "CreatureAction.json", "attacks": "CreatureActionAttack.json"}}}'::jsonb,'','','','',true,true,true,true,true,true,7);
INSERT INTO rpg_systems (id,display_name,chain_tag,path_suffix,is_active,ruleset,target_seconds,reading_level,no_homebrew_mechanics,default_length,spice_rate,persona_default,voiceover_default_voice_pack_id,voiceover_default_tts_voice_id,active_srd_path,srd_pdf_path,reference_sources,bg_image_prompt_prefix,bg_image_prompt_suffix,music_prompt_prefix,music_prompt_suffix,enable_ai,enable_ai_script,enable_tts,enable_bg_image,enable_bg_music,enable_pdf_flavor,tts_voice_variety_lookback_days) VALUES ('shadowdark','Shadowdark','Shadowdark','_shadowdark',true,'shadowdark_v4_8',55,'general',true,'shorts',0.6,'wry_vet','voice-shadowdark-ref','onyx','reference/systems/shadowdark/active','reference/systems/shadowdark/source_pdfs/Shadowdark_RPG_-_V4-8.pdf','{"items": {"file": "Item.json"}, "rules": {"file": "Rule.json"}, "spells": {"file": "Spell.json", "joins": {"casting_options": "SpellCastingOption.json"}}, "classes": {"file": "CharacterClass.json"}, "creatures": {"file": "Creature.json", "joins": {"traits": "CreatureTrait.json", "actions": "CreatureAction.json", "attacks": "CreatureActionAttack.json"}}}'::jsonb,'shadowdark aesthetic, dangerous dungeon crawl, torchlight and deep shadow, gritty old-school fantasy','','shadowdark tone, tense dungeon exploration, low-magic peril, restrained ominous ambience','',true,true,true,true,true,true,7);
-- rpg_systems: 2 rows

-- system_weekly_spine
DELETE FROM system_weekly_spine;
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('dnd5e','fri','encounter_seed');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('dnd5e','mon','monster_tactic');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('dnd5e','sat','rules_myth');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('dnd5e','sun','class_spotlight');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('dnd5e','thu','item_spotlight');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('dnd5e','tue','spell_use_case');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('dnd5e','wed','rules_ruling');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('shadowdark','fri','rules_myth');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('shadowdark','mon','monster_tactic');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('shadowdark','sat','spell_use_case');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('shadowdark','sun','class_spotlight');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('shadowdark','thu','encounter_seed');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('shadowdark','tue','rules_ruling');
INSERT INTO system_weekly_spine (system_id,day_of_week,category) VALUES ('shadowdark','wed','item_spotlight');
-- system_weekly_spine: 14 rows

-- system_categories
DELETE FROM system_categories;
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','character_class_spotlight','class_mentor',NULL,ARRAY['friendly_vet','gritty_dm','rules_lawyer'],ARRAY['level_1_choice','party_role','survivability','exploration_edge','table_etiquette']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','character_micro_tip','class_mentor',ARRAY['heroic','dry'],ARRAY['friendly_vet','gritty_dm','rules_lawyer'],ARRAY['level_1_choice','party_role','survivability','exploration_edge','table_etiquette']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','class_spotlight','class_mentor',ARRAY['heroic','dry'],ARRAY['friendly_vet','gritty_dm','rules_lawyer'],ARRAY['early_power_spike','subclass_identity','resource_breakpoint','party_role_pivot','progression_trap']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','dungeoneering_encounter','dm_story_coach',NULL,ARRAY['gritty_dm','friendly_vet','rules_lawyer'],ARRAY['three_beats','twist','terrain_feature','time_pressure','moral_choice']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','encounter_seed','dm_story_coach',ARRAY['gritty','heroic'],ARRAY['gritty_dm','friendly_vet','rules_lawyer'],ARRAY['three_beats','twist','terrain_feature','time_pressure','moral_choice']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','gm_tip','rules_referee',NULL,ARRAY['rules_lawyer','friendly_vet','gritty_dm'],ARRAY['common_table_mistake','fast_ruling','edge_case','dm_fairness_tip','player_tip']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','item_spotlight','clever_table_vet',ARRAY['dry','heroic'],ARRAY['friendly_vet','rules_lawyer','gritty_dm'],ARRAY['best_user','clever_use','drawback_watchout','dm_counterplay','story_hook']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','monster_tactic','tactical_analyst',ARRAY['gritty','dry'],ARRAY['gritty_dm','rules_lawyer','friendly_vet'],ARRAY['how_it_wins','common_mistake','counterplay']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','overworld_encounter','dm_story_coach',NULL,ARRAY['gritty_dm','friendly_vet','rules_lawyer'],ARRAY['three_beats','twist','terrain_feature','time_pressure','moral_choice']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','roleplaying_tip','class_mentor',NULL,ARRAY['friendly_vet','gritty_dm','rules_lawyer'],ARRAY['level_1_choice','party_role','survivability','exploration_edge','table_etiquette']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','rules_myth','rules_referee',ARRAY['dry'],ARRAY['rules_lawyer','friendly_vet','gritty_dm'],ARRAY['myth_vs_rule','why_people_get_it_wrong','quick_example','dm_callout']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','rules_ruling','rules_referee',ARRAY['dry'],ARRAY['rules_lawyer','friendly_vet','gritty_dm'],ARRAY['common_table_mistake','fast_ruling','edge_case','dm_fairness_tip','player_tip']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('dnd5e','spell_use_case','clever_table_vet',ARRAY['dry','heroic'],ARRAY['friendly_vet','rules_lawyer','gritty_dm'],ARRAY['best_moment','common_misplay','dm_twist','combo_pairing','upcast_tip','dm_counterplay']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('shadowdark','character_micro_tip','class_mentor',ARRAY['gritty','dry'],ARRAY['torchbearer_ref','grim_warden','strict_referee'],ARRAY['level_1_choice','party_role','survivability']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('shadowdark','class_spotlight','class_mentor',ARRAY['gritty','dry'],ARRAY['torchbearer_ref','grim_warden','strict_referee'],ARRAY['early_power_spike','party_role_pivot','progression_trap']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('shadowdark','encounter_seed','dm_story_coach',ARRAY['ominous','gritty'],ARRAY['grim_warden','torchbearer_ref','strict_referee'],ARRAY['three_beats','twist','time_pressure','moral_choice']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('shadowdark','item_spotlight','dungeon_gear_mentor',ARRAY['gritty','dry'],ARRAY['torchbearer_ref','grim_warden','strict_referee'],ARRAY['clever_use','best_user','drawback_watchout']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('shadowdark','monster_tactic','tactical_analyst',ARRAY['gritty','ominous'],ARRAY['grim_warden','strict_referee','torchbearer_ref'],ARRAY['how_it_wins','common_mistake','counterplay']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('shadowdark','rules_myth','rules_referee',ARRAY['dry','gritty'],ARRAY['strict_referee','torchbearer_ref','grim_warden'],ARRAY['myth_vs_rule','quick_example','dm_callout']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('shadowdark','rules_ruling','rules_referee',ARRAY['dry','gritty'],ARRAY['strict_referee','torchbearer_ref','grim_warden'],ARRAY['fast_ruling','common_table_mistake','edge_case']);
INSERT INTO system_categories (system_id,category,persona,tones,voices,angles) VALUES ('shadowdark','spell_use_case','arcane_survival_coach',ARRAY['gritty','dry'],ARRAY['torchbearer_ref','strict_referee','grim_warden'],ARRAY['best_moment','common_misplay','dm_twist']);
-- system_categories: 21 rows

-- system_category_angle_weights
DELETE FROM system_category_angle_weights;
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','character_micro_tip','table_etiquette',1);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','character_micro_tip','level_1_choice',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','character_micro_tip','party_role',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','character_micro_tip','survivability',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','character_micro_tip','exploration_edge',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','class_spotlight','progression_trap',1);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','class_spotlight','party_role_pivot',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','class_spotlight','resource_breakpoint',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','class_spotlight','subclass_identity',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','class_spotlight','early_power_spike',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','encounter_seed','moral_choice',1);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','encounter_seed','three_beats',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','encounter_seed','twist',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','encounter_seed','terrain_feature',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','encounter_seed','time_pressure',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','item_spotlight','best_user',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','item_spotlight','clever_use',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','item_spotlight','drawback_watchout',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','item_spotlight','dm_counterplay',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','item_spotlight','story_hook',1);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','monster_tactic','how_it_wins',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','monster_tactic','roleplay_hook',1);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','monster_tactic','party_level_scaling',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','monster_tactic','terrain_synergy',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','monster_tactic','how_to_counter',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','rules_myth','myth_vs_rule',4);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','rules_myth','why_people_get_it_wrong',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','rules_myth','quick_example',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','rules_myth','dm_callout',1);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','rules_ruling','player_tip',1);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','rules_ruling','dm_fairness_tip',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','rules_ruling','edge_case',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','rules_ruling','fast_ruling',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','rules_ruling','common_table_mistake',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','spell_use_case','dm_counterplay',1);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','spell_use_case','upcast_tip',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','spell_use_case','common_mistake',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','spell_use_case','combo_pairing',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('dnd5e','spell_use_case','best_moment',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','class_spotlight','resource_breakpoint',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','class_spotlight','early_power_spike',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','class_spotlight','party_role_pivot',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','class_spotlight','progression_trap',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','encounter_seed','three_beats',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','encounter_seed','moral_choice',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','encounter_seed','time_pressure',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','encounter_seed','twist',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','item_spotlight','best_user',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','item_spotlight','story_hook',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','item_spotlight','drawback_watchout',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','item_spotlight','clever_use',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','monster_tactic','terrain_synergy',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','monster_tactic','how_it_wins',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','monster_tactic','how_to_counter',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','monster_tactic','common_mistake',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','rules_myth','myth_vs_rule',4);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','rules_myth','why_people_get_it_wrong',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','rules_myth','quick_example',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','rules_ruling','common_table_mistake',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','rules_ruling','player_tip',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','rules_ruling','edge_case',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','rules_ruling','fast_ruling',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','spell_use_case','best_moment',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','spell_use_case','common_mistake',3);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','spell_use_case','dm_counterplay',2);
INSERT INTO system_category_angle_weights (system_id,category,angle,weight) VALUES ('shadowdark','spell_use_case','combo_pairing',2);
-- system_category_angle_weights: 66 rows

-- system_tones
DELETE FROM system_tones;
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('dnd5e','deadpan','voice-wry-vet',ARRAY['ash','coral','verse','sage']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('dnd5e','dry','voice-wry-vet',ARRAY['onyx','nova','ash','coral']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('dnd5e','gritty','voice-gritty-dm',ARRAY['onyx','echo']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('dnd5e','heroic','voice-class-mentor',ARRAY['nova','fable']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('dnd5e','punchy','voice-wry-vet',ARRAY['nova','echo','ballad','shimmer']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('dnd5e','sardonic','voice-wry-vet',ARRAY['onyx','shimmer','fable','alloy']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('dnd5e','wry','voice-wry-vet',ARRAY['fable','shimmer','echo','sage']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('shadowdark','deadpan','voice-wry-vet',ARRAY['ash','coral','verse','sage']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('shadowdark','dry','voice-wry-vet',ARRAY['onyx','nova','ash','coral']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('shadowdark','gritty','voice-shadowdark-grit',ARRAY['onyx','echo']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('shadowdark','ominous','voice-shadowdark-ominous',ARRAY['onyx','fable']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('shadowdark','punchy','voice-wry-vet',ARRAY['nova','echo','ballad','shimmer']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('shadowdark','sardonic','voice-wry-vet',ARRAY['onyx','shimmer','fable','alloy']);
INSERT INTO system_tones (system_id,tone,voice_pack_id,tts_voice_ids) VALUES ('shadowdark','wry','voice-wry-vet',ARRAY['fable','shimmer','echo','sage']);
-- system_tones: 14 rows

-- system_voices
DELETE FROM system_voices;
INSERT INTO system_voices (system_id,voice_name,tts_voice_ids,hooks,ctas) VALUES ('dnd5e','friendly_vet',ARRAY['alloy','ash'],ARRAY['Old-school kit check: {name}.','Dungeon kit spotlight: {name}.'],ARRAY['DMs: drop one in the dungeon and watch the party start thinking like engineers.','Players: buy this before your next shiny weapon.']);
INSERT INTO system_voices (system_id,voice_name,tts_voice_ids,hooks,ctas) VALUES ('dnd5e','gritty_dm',ARRAY['onyx','echo'],ARRAY['In the dark, rope beats steel: {name}.','This is how you move the world: {name}.'],ARRAY['DMs: make the environment heavy. Let tools matter.','Players: win fights by winning terrain first.']);
INSERT INTO system_voices (system_id,voice_name,tts_voice_ids,hooks,ctas) VALUES ('dnd5e','rules_lawyer',ARRAY['sage','ash'],ARRAY['Mechanics moment: {name}.','Rules-forward pick: {name}.'],ARRAY['If you want ‘smart play’, reward prep like this.','Track time, anchors, and positioning—this is where it earns its keep.']);
INSERT INTO system_voices (system_id,voice_name,tts_voice_ids,hooks,ctas) VALUES ('shadowdark','grim_warden',NULL,ARRAY['In the dark, {name} matters.','Hard lesson: {name}.'],ARRAY['DMs: reward caution and punish noise.','Players: win with prep, not bravado.']);
INSERT INTO system_voices (system_id,voice_name,tts_voice_ids,hooks,ctas) VALUES ('shadowdark','strict_referee',NULL,ARRAY['Ruling check: {name}.','Table call: {name}.'],ARRAY['Keep rulings fast, clear, and consistent.','Call intent first, then roll.']);
INSERT INTO system_voices (system_id,voice_name,tts_voice_ids,hooks,ctas) VALUES ('shadowdark','torchbearer_ref',NULL,ARRAY['Torchlight briefing: {name}.','Dungeon brief: {name}.'],ARRAY['DMs: put pressure on time, light, and noise.','Players: solve for survival before style points.']);
-- system_voices: 6 rows

-- system_voice_category_lines
DELETE FROM system_voice_category_lines;
INSERT INTO system_voice_category_lines (system_id,voice_name,category,hooks,ctas) VALUES ('dnd5e','friendly_vet','monster_tactic',ARRAY['Monster check: {name}.','Table troublemaker: {name}.'],ARRAY['DMs: run it like it wants to win, not like it wants to die politely.','Players: solve the monster, don’t just swing at it.']);
INSERT INTO system_voice_category_lines (system_id,voice_name,category,hooks,ctas) VALUES ('dnd5e','friendly_vet','spell_use_case',ARRAY['Spell play: {name}.','Pocket magic: {name}.'],ARRAY['DMs: let clever casting change the scene.','Players: don’t cast it—*aim* it.']);
INSERT INTO system_voice_category_lines (system_id,voice_name,category,hooks,ctas) VALUES ('dnd5e','gritty_dm','monster_tactic',ARRAY['In the dark, {name} is a problem.','Tonight’s lesson: {name}.'],ARRAY['DMs: hit hard, then disengage—predators don’t trade blows.','Players: control space or bleed for it.']);
INSERT INTO system_voice_category_lines (system_id,voice_name,category,hooks,ctas) VALUES ('dnd5e','gritty_dm','spell_use_case',ARRAY['Magic with teeth: {name}.','When it matters: {name}.'],ARRAY['DMs: make magic costly, not pointless.','Players: spend the slot when it swings the fight.']);
INSERT INTO system_voice_category_lines (system_id,voice_name,category,hooks,ctas) VALUES ('dnd5e','rules_lawyer','monster_tactic',ARRAY['Statblock truth: {name}.','Tactics note: {name}.'],ARRAY['DMs: reward good positioning; punish sloppy clustering.','Players: deny advantage, deny actions, deny turns.']);
INSERT INTO system_voice_category_lines (system_id,voice_name,category,hooks,ctas) VALUES ('dnd5e','rules_lawyer','spell_use_case',ARRAY['Spell timing note: {name}.','Rules nugget: {name}.'],ARRAY['DMs: enforce components and concentration—spells get sharper.','Players: read the target line twice, then cast.']);
-- system_voice_category_lines: 6 rows

-- system_personas
DELETE FROM system_personas;
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('dnd5e','class_mentor','Encouraging, role-aware class coaching focused on better decisions.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('dnd5e','clever_table_vet','Practical table wisdom with a bit of personality and momentum.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('dnd5e','dm_story_coach','Clear, dramatic, and practical DM guidance with concrete stakes.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('dnd5e','rules_referee','Crisp, fair, and consistent rules adjudication voice.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('dnd5e','table_coach','Friendly veteran table coach balancing clarity and fun.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('dnd5e','tactical_analyst','Serious threat-first tactical framing with minimal fluff.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('dnd5e','wry_vet','Dry, world-weary veteran DM who has run this encounter a hundred times. Authoritative, specific, slightly sardonic. No hype. No hand-holding. Calls the table''s bad habits what they are. Assumes the reader has been around.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('shadowdark','arcane_survival_coach','Spell use focused on survival, tempo, and risk control.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('shadowdark','class_mentor','Role-focused class guidance with concrete play impact.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('shadowdark','dm_story_coach','Tight encounter framing with pressure and consequence.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('shadowdark','dungeon_gear_mentor','Resource-first gear coaching for dangerous exploration.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('shadowdark','rules_referee','Crisp rulings that keep momentum and fairness.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('shadowdark','tactical_analyst','Threat-first tactics with strict economy of action.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('shadowdark','torchbearer_referee','Practical, high-stakes guidance for lethal dungeon play.');
INSERT INTO system_personas (system_id,persona,one_liner) VALUES ('shadowdark','wry_vet','Dry, world-weary veteran DM who has run this encounter a hundred times. Authoritative, specific, slightly sardonic. No hype. No hand-holding. Calls the table''s bad habits what they are. Assumes the reader has been around.');
-- system_personas: 15 rows
